channels:
- conda-forge
dependencies:
- python=3.11.6
- pip<=25.0.1
- pip:
  - mlflow==2.21.3
  - category-encoders==2.7.0
  - cloudpickle==3.1.1
  - numpy==1.26.4
  - pandas==2.1.4
  - psutil==6.0.0
  - scikit-learn==1.4.2
  - scipy==1.11.4
name: mlflow-env
