version: '3.9'

services:
  web:
    build: .
    container_name: django_app
    command: uvicorn django_project.asgi:application --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DEBUG=1
      - DB_NAME=PENSight_db
      - DB_USER=postgres
      - DB_PASSWORD=bismillah
      - DB_HOST=db
      - DB_PORT=5432
    networks:
      - django_network

  db:
    image: postgres:14
    container_name: postgres_db
    environment:
      POSTGRES_DB: PENSight_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: bismillah
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - django_network

networks:
  django_network:

volumes:
  postgres_data:
